import type { Project } from "./types";

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    client_id: "1",
    name: "Banco de capacitores 150 kVAR",
    type: "capacitor_bank",
    status: "approved",
    investment: 185000,
    estimated_savings: 142800,
    roi_months: 15.5,
    start_date: "2026-05-01",
  },
  {
    id: "proj-2",
    client_id: "1",
    name: "Retrofit LED nave de producción",
    type: "led",
    status: "proposal",
    investment: 320000,
    estimated_savings: 168000,
    roi_months: 22.9,
    start_date: "",
  },
  {
    id: "proj-3",
    client_id: "2",
    name: "Sistema solar FV 50 kWp",
    type: "solar_pv",
    status: "in_progress",
    investment: 850000,
    estimated_savings: 312000,
    roi_months: 32.7,
    start_date: "2026-03-15",
  },
  {
    id: "proj-4",
    client_id: "3",
    name: "VFDs para bombas de agua",
    type: "vfd",
    status: "installed",
    investment: 210000,
    estimated_savings: 96000,
    roi_months: 26.3,
    start_date: "2025-11-01",
  },
  {
    id: "proj-5",
    client_id: "1",
    name: "BESS peak shaving 100 kWh",
    type: "bess",
    status: "proposal",
    investment: 1200000,
    estimated_savings: 384000,
    roi_months: 37.5,
    start_date: "",
  },
];
